Repository pyroscope-io/helm-chart, pull requests merged in 2021-08, with the labels that each got.

#6 fix: ingress
  chart/pyroscope/Chart.yaml
  chart/pyroscope/README.md
  chart/pyroscope/templates/ingress.yaml
  chart/pyroscope/values.yaml
Labels: bug

#8 docs: improve readme with instructions to enable persistence
  chart/pyroscope/README.md
  chart/pyroscope/README.md.gotmpl
  chart/pyroscope/values.yaml
Labels: documentation, enhancement

#9 Fix service annotations
  chart/pyroscope/Chart.yaml
  chart/pyroscope/README.md
  chart/pyroscope/templates/service.yaml
Labels: bug

#11 Add support for extra volumes
  chart/pyroscope/Chart.yaml
  chart/pyroscope/README.md
  chart/pyroscope/templates/deployment.yaml
  chart/pyroscope/values.yaml
Labels: enhancement

#12 Add support for custom ingress rules
  chart/pyroscope/Chart.yaml
  chart/pyroscope/README.md
  chart/pyroscope/templates/ingress.yaml
  chart/pyroscope/values.yaml
Labels: enhancement
